name = "cf-drop"
main = "src/index.ts"
compatibility_date = "2025-01-02"

assets = { directory = "web/dist", binding = "ASSETS" }
# compatibility_flags = [ "nodejs_compat" ]

# [[d1_databases]]
# binding = "DB"
# database_name = "cf-drop"
# database_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "cf-drop"



# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1